CREATE TABLE Departments (
  Id INT IDENTITY PRIMARY KEY,
  Name NVARCHAR(150) NOT NULL,
  Description NVARCHAR(300) NULL,
  IsActive BIT NOT NULL DEFAULT 1,
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  UpdatedAt DATETIME2 NULL
);

CREATE TABLE Employees (
  Id INT IDENTITY PRIMARY KEY,
  PublicToken UNIQUEIDENTIFIER NOT NULL DEFAULT NEWID(),
  Name NVARCHAR(150) NOT NULL,
  DepartmentId INT NOT NULL FOREIGN KEY REFERENCES Departments(Id),
  EmployeeCode NVARCHAR(50) NULL,
  PhoneOrExtension NVARCHAR(50) NULL,
  IsActive BIT NOT NULL DEFAULT 1,
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  UpdatedAt DATETIME2 NULL
);

CREATE TABLE Roles (
  Id INT IDENTITY PRIMARY KEY,
  Name NVARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE InternalUsers (
  Id INT IDENTITY PRIMARY KEY,
  Username NVARCHAR(80) NOT NULL UNIQUE,
  FullName NVARCHAR(150) NOT NULL,
  PasswordHash NVARCHAR(255) NOT NULL,
  RoleId INT NOT NULL FOREIGN KEY REFERENCES Roles(Id),
  DepartmentId INT NULL FOREIGN KEY REFERENCES Departments(Id),
  IsActive BIT NOT NULL DEFAULT 1,
  RequirePasswordChange BIT NOT NULL DEFAULT 0,
  LastLoginAt DATETIME2 NULL,
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  UpdatedAt DATETIME2 NULL
);

CREATE TABLE Materials (
  Id INT IDENTITY PRIMARY KEY,
  ItemCode NVARCHAR(80) NULL,
  Name NVARCHAR(200) NOT NULL,
  Description NVARCHAR(500) NULL,
  IsActive BIT NOT NULL DEFAULT 1,
  IsRequestable BIT NOT NULL DEFAULT 1,
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  UpdatedAt DATETIME2 NULL
);

CREATE UNIQUE INDEX UX_Materials_ItemCode ON Materials(ItemCode) WHERE ItemCode IS NOT NULL;

CREATE TABLE RequisitionStatuses (
  Id INT IDENTITY PRIMARY KEY,
  Code NVARCHAR(50) NOT NULL UNIQUE,
  Name NVARCHAR(80) NOT NULL,
  SortOrder INT NOT NULL,
  IsFinal BIT NOT NULL DEFAULT 0
);

CREATE TABLE Requisitions (
  Id INT IDENTITY PRIMARY KEY,
  Code NVARCHAR(30) NOT NULL UNIQUE,
  EmployeeId INT NOT NULL FOREIGN KEY REFERENCES Employees(Id),
  StatusId INT NOT NULL FOREIGN KEY REFERENCES RequisitionStatuses(Id),
  Priority NVARCHAR(20) NOT NULL DEFAULT 'Media',
  GeneralComment NVARCHAR(1000) NULL,
  AssignedToUserId INT NULL FOREIGN KEY REFERENCES InternalUsers(Id),
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  UpdatedAt DATETIME2 NULL,
  ClosedAt DATETIME2 NULL,
  CancelledAt DATETIME2 NULL,
  CancelReason NVARCHAR(1000) NULL,
  RejectedAt DATETIME2 NULL,
  RejectReason NVARCHAR(1000) NULL
);

CREATE TABLE RequisitionItems (
  Id INT IDENTITY PRIMARY KEY,
  RequisitionId INT NOT NULL FOREIGN KEY REFERENCES Requisitions(Id),
  MaterialId INT NULL FOREIGN KEY REFERENCES Materials(Id),
  ManualMaterialName NVARCHAR(200) NULL,
  QuantityRequested DECIMAL(18,4) NOT NULL,
  QuantityApproved DECIMAL(18,4) NULL,
  QuantityDelivered DECIMAL(18,4) NULL DEFAULT 0,
  Comment NVARCHAR(500) NULL,
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE RequisitionComments (
  Id INT IDENTITY PRIMARY KEY,
  RequisitionId INT NOT NULL FOREIGN KEY REFERENCES Requisitions(Id),
  AuthorType NVARCHAR(20) NOT NULL,
  EmployeeId INT NULL FOREIGN KEY REFERENCES Employees(Id),
  InternalUserId INT NULL FOREIGN KEY REFERENCES InternalUsers(Id),
  Message NVARCHAR(2000) NOT NULL,
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE RequisitionHistory (
  Id INT IDENTITY PRIMARY KEY,
  RequisitionId INT NOT NULL FOREIGN KEY REFERENCES Requisitions(Id),
  Action NVARCHAR(80) NOT NULL,
  PreviousStatusId INT NULL FOREIGN KEY REFERENCES RequisitionStatuses(Id),
  NewStatusId INT NULL FOREIGN KEY REFERENCES RequisitionStatuses(Id),
  PerformedByType NVARCHAR(20) NOT NULL,
  EmployeeId INT NULL FOREIGN KEY REFERENCES Employees(Id),
  InternalUserId INT NULL FOREIGN KEY REFERENCES InternalUsers(Id),
  Notes NVARCHAR(1000) NULL,
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME()
);

CREATE TABLE Notifications (
  Id INT IDENTITY PRIMARY KEY,
  RecipientType NVARCHAR(20) NOT NULL,
  EmployeeId INT NULL FOREIGN KEY REFERENCES Employees(Id),
  InternalUserId INT NULL FOREIGN KEY REFERENCES InternalUsers(Id),
  RoleId INT NULL FOREIGN KEY REFERENCES Roles(Id),
  RequisitionId INT NULL FOREIGN KEY REFERENCES Requisitions(Id),
  Title NVARCHAR(150) NOT NULL,
  Message NVARCHAR(500) NOT NULL,
  Type NVARCHAR(50) NOT NULL,
  IsRead BIT NOT NULL DEFAULT 0,
  CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
  ReadAt DATETIME2 NULL
);
